# Generated by Django 6.0.1 on 2026-04-04 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(choices=[('MSCE (Malawi School Certificate of Education)', 'MSCE (Malawi School Certificate of Education)'), ('JCE (Junior Certificate of Education)', 'JCE (Junior Certificate of Education)'), ('O-Level', 'O-Level'), ('A-Level', 'A-Level'), ('IGCSE', 'IGCSE'), ('Other', 'Other')], max_length=100)),
                ('centre_number', models.CharField(max_length=50)),
                ('exam_number', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'subject_records',
                'ordering': ['-year', 'subject'],
            },
        ),
    ]
