# Generated by Django 6.0.1 on 2026-04-18 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammeChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_number', models.IntegerField()),
                ('selected_at', models.DateTimeField(auto_now_add=True)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.programme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programme_choices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['choice_number'],
                'unique_together': {('user', 'choice_number')},
            },
        ),
    ]
