# Generated by Django 6.0.1 on 2026-04-18 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_programmechoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programmechoice',
            old_name='selected_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='programmechoice',
            name='programme',
        ),
        migrations.AddField(
            model_name='programmechoice',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='programmechoice',
            name='department',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='programmechoice',
            name='duration',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='programmechoice',
            name='programme_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programmechoice',
            name='programme_name',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
