# Generated by Django 6.0.1 on 2026-04-21 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0011_referee'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='programme_type',
            field=models.CharField(blank=True, choices=[('upgrading', 'Upgrading'), ('non-generic', 'Non-Generic'), ('generic', 'Generic')], help_text='Type of programme: upgrading, non-generic, or generic', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='programme',
            name='school',
            field=models.CharField(blank=True, help_text='School/Faculty offering the programme', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='programme',
            name='study_mode',
            field=models.CharField(blank=True, choices=[('full time', 'Full Time'), ('weekend', 'Weekend'), ('evening', 'Evening'), ('online', 'Online'), ('odel', 'ODeL')], help_text='Study mode: full time, weekend, evening, online, or odel', max_length=20, null=True),
        ),
    ]
