# Generated by Django 6.0.4 on 2026-04-24 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0013_applicant_reference_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='id_card',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='id_card_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='id_card_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='msce',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='msce_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='msce_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='payment_proof',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='payment_proof_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='payment_proof_size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
