# Generated by Django 6.0.4 on 2026-04-27 18:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0014_applicant_id_card_applicant_id_card_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='selection_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
