# Generated by Django 6.0.4 on 2026-04-27 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0015_alter_applicant_selection_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='ml_confidence',
            field=models.FloatField(blank=True, help_text='ML confidence score (0.0 to 1.0)', null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='ml_decision',
            field=models.CharField(blank=True, help_text="ML decision: 'approve', 'reject', or 'review'", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='ml_factors',
            field=models.JSONField(blank=True, help_text='JSON object storing reasons and risk factors', null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='ml_priority',
            field=models.CharField(blank=True, help_text="Priority level: 'High', 'Medium', or 'Low'", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='ml_probability',
            field=models.FloatField(blank=True, help_text='Success probability (0.0 to 1.0)', null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='ml_processed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when ML analysis was performed', null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='ml_raw_response',
            field=models.JSONField(blank=True, help_text='Complete raw ML response JSON', null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='ml_recommendation',
            field=models.TextField(blank=True, help_text='ML recommendation text', null=True),
        ),
    ]
