# Generated by Django 6.0.4 on 2026-04-27 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0016_applicant_ml_confidence_applicant_ml_decision_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachingSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
                ('subject_code', models.CharField(blank=True, max_length=10, null=True)),
                ('teaching_level', models.CharField(choices=[('junior', 'Junior Secondary (Form 1-2)'), ('senior', 'Senior Secondary (Form 3-4)'), ('both', 'Both Junior & Senior')], default='both', max_length=10)),
                ('is_major', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_subjects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teaching Subject',
                'verbose_name_plural': 'Teaching Subjects',
                'db_table': 'teaching_subjects',
                'ordering': ['subject_name'],
            },
        ),
    ]
