# Generated by Django 6.0.4 on 2026-05-01 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0018_document_description_document_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(help_text='e.g., 2024, 2024/2025', max_length=9)),
                ('intake_period', models.CharField(help_text='e.g., September Intake, January Intake', max_length=50)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_open', models.BooleanField(default=True)),
                ('programmes_offered', models.JSONField(default=list, help_text='List of programme names offered')),
                ('max_applications', models.IntegerField(default=1000, help_text='Maximum number of applications to accept')),
                ('current_applications', models.IntegerField(default=0, help_text='Current number of applications received')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, help_text='User who created this window', max_length=255)),
            ],
            options={
                'verbose_name': 'Application Window',
                'verbose_name_plural': 'Application Windows',
                'db_table': 'application_windows',
                'ordering': ['-academic_year', '-created_at'],
                'indexes': [models.Index(fields=['is_open', 'start_date', 'end_date'], name='application_is_open_290ad9_idx'), models.Index(fields=['academic_year'], name='application_academi_adb056_idx'), models.Index(fields=['intake_period'], name='application_intake__dea88d_idx')],
            },
        ),
    ]
