# Generated by Django 6.0.5 on 2026-03-23 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0019_applicationwindow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='auto_processed',
            field=models.BooleanField(default=False, help_text='Whether this application was auto-processed by ML'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection if status is rejected', null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('password_change', 'Password Change'), ('profile_update', 'Profile Update'), ('account_deletion', 'Account Deletion'), ('session_logout', 'Session Logout'), ('settings_update', 'Settings Update'), ('data_export', 'Data Export'), ('backup_created', 'Backup Created'), ('user_deletion', 'User Deletion'), ('role_update', 'Role Update')], max_length=100),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_log_entries', to=settings.AUTH_USER_MODEL),
        ),
    ]
