# Generated by Django 6.0.5 on 2026-05-08 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0020_applicant_auto_processed_applicant_rejection_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EligibilityCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_subjects', models.IntegerField(default=6)),
                ('min_credits', models.IntegerField(default=4)),
                ('max_points', models.IntegerField(default=30)),
                ('required_subjects', models.JSONField(default=list)),
                ('preferred_subjects', models.JSONField(default=list)),
                ('subject_weights', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_criteria', to=settings.AUTH_USER_MODEL)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_criteria', to='API.programme')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_criteria', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EligibilityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programme_id', models.IntegerField()),
                ('programme_name', models.CharField(max_length=255)),
                ('action', models.CharField(max_length=50)),
                ('previous_status', models.BooleanField()),
                ('new_status', models.BooleanField()),
                ('reason', models.TextField(blank=True)),
                ('performed_by', models.CharField(max_length=255)),
                ('eligibility_score', models.FloatField(default=0)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_logs', to='API.applicant')),
            ],
        ),
        migrations.CreateModel(
            name='EligibilityOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programme_id', models.IntegerField()),
                ('eligible', models.BooleanField()),
                ('reason', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('performed_by', models.CharField(max_length=255)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_overrides', to='API.applicant')),
            ],
        ),
    ]
