# Generated by Django 6.0.5 on 2026-05-13 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0021_eligibilitycriteria_eligibilitylog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='rejection_details',
            field=models.JSONField(blank=True, default=dict, help_text='Detailed rejection information including factors and recommendations', null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, help_text='When the application was reviewed', null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='reviewed_by',
            field=models.CharField(blank=True, help_text='User who reviewed the application', max_length=255, null=True),
        ),
    ]
