# Generated by Django 6.0.5 on 2026-05-13 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0022_applicant_rejection_details_applicant_reviewed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('applicant', 'Applicant'), ('admin', 'Administrator'), ('admission_officer', 'Admission Officer'), ('committee', 'Committee Member'), ('staff', 'Staff'), ('guest', 'Guest')], default='applicant', help_text='User role for access control', max_length=50),
        ),
    ]
