# Generated by Django 6.0.5 on 2026-05-13 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0023_applicant_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='documents_valid',
            field=models.BooleanField(blank=True, default=False, help_text="Whether the applicant's documents have been verified", null=True),
        ),
    ]
