# Generated by Django 6.0.5 on 2026-05-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0024_applicant_documents_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='id_card_base64',
            field=models.TextField(blank=True, help_text='Base64 encoded ID card for API transfer', null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='id_card_content',
            field=models.BinaryField(blank=True, help_text='Binary content of ID card', null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='id_card_type',
            field=models.CharField(blank=True, help_text='MIME type (e.g., image/jpeg)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='msce_base64',
            field=models.TextField(blank=True, help_text='Base64 encoded MSCE certificate for API transfer', null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='msce_content',
            field=models.BinaryField(blank=True, help_text='Binary content of MSCE certificate', null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='msce_type',
            field=models.CharField(blank=True, help_text='MIME type (e.g., application/pdf)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='payment_proof_base64',
            field=models.TextField(blank=True, help_text='Base64 encoded payment proof for API transfer', null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='payment_proof_content',
            field=models.BinaryField(blank=True, help_text='Binary content of payment proof', null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='payment_proof_type',
            field=models.CharField(blank=True, help_text='MIME type (e.g., application/pdf, image/jpeg)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='committeemember',
            name='profile_image_base64',
            field=models.TextField(blank=True, help_text='Base64 encoded profile image for API transfer', null=True),
        ),
        migrations.AddField(
            model_name='committeemember',
            name='profile_image_content',
            field=models.BinaryField(blank=True, help_text='Binary content of profile image', null=True),
        ),
        migrations.AddField(
            model_name='committeemember',
            name='profile_image_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='committeemember',
            name='profile_image_type',
            field=models.CharField(blank=True, help_text='MIME type (e.g., image/jpeg, image/png)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='file_base64',
            field=models.TextField(blank=True, help_text='Base64 encoded document for API transfer', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='file_content',
            field=models.BinaryField(blank=True, help_text='Binary content of document', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='file_mime_type',
            field=models.CharField(blank=True, help_text='MIME type', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='file_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='deposit_slip_base64',
            field=models.TextField(blank=True, help_text='Base64 encoded deposit slip for API transfer', null=True),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='deposit_slip_content',
            field=models.BinaryField(blank=True, help_text='Binary content of deposit slip', null=True),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='deposit_slip_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='deposit_slip_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='deposit_slip_type',
            field=models.CharField(blank=True, help_text='MIME type (e.g., image/jpeg, application/pdf)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='deposit_slip_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
