# Generated by Django 5.2.8 on 2025-12-18 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_programme_options_remove_applicant_firstname_and_more'),
    ]

    operations = [
    ]
